class CharacterSheet {
    'character': undefined,
    'actualAge': undefined,
    'background': undefined,
    'faction': undefined,
    'currentMorph': undefined,
    'genderIdentity': undefined,
    'currentMoxie': undefined,
    'rezPoints': undefined,
    'motivations': undefined,
    'aptitudes': {
        'base': {
            'cognition': undefined,
            'coordination': undefined,
            'intuition': undefined,
            'reflexes': undefined,
            'savvy': undefined,
            'somatics': undefined,
            'willpower': undefined
        },
        'morphBonus': {
            'cognition': undefined,
            'coordination': undefined,
            'intuition': undefined,
            'reflexes': undefined,
            'savvy': undefined,
            'somatics': undefined,
            'willpower': undefined
        },
    },
    'stats': {
        'moxie': undefined,
        'traumaThreshhold': undefined,
        'lucidity': undefined,
        'insanityRating': undefined,
        'woundThreshold': undefined,
        'durability': undefined,
        'deathRating': undefined,
        'initiative': undefined,
        'speed': undefined,
        'damageBonus': undefined
    },
    'damageStress': {
        'damage': undefined,
        'wounds': undefined,
        'stress': undefined,
        'trauma': undefined
    },
    'activeSkills': {
        'animalHandling': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'beamWeapons': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'blades': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'climbing': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'clubs': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'control': {
            'linkedApt': 'willpower',
            'defaulting': false,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'deception': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'demolitions': {
            'linkedApt': 'cognition',
            'defaulting': false,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'disguise': {
            'linkedApt': 'intuition',
            'defaulting': false,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticMelee0': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticMelee1': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticMelee2': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticMelee3': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticMelee4': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticRanged0': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticRanged1': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticRanged2': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticRanged3': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'exoticRanged4': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'flight': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'fray': {
            'linkedApt': 'reflexes',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'freeFall': {
            'linkedApt': 'reflexes',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'freerunning': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'gunnery': {
            'linkedApt': 'intuition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'hardware0': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'hardware1': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'hardware2': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'hardware3': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'hardware4': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'impersonation': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'infiltration': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'infosec': {
            'linkedApt': 'cognition',
            'defaulting': false,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'interfacing': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'intimidation': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'investigation': {
            'linkedApt': 'intuition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'kinesics': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'kineticWeapons': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'medicine0': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'medicine1': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'medicine2': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'medicine3': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'medicine4': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'navigation': {
            'linkedApt': 'intuition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'networking0': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'networking1': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'networking2': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'networking3': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'networking4': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'palming': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'perception': {
            'linkedApt': 'intuition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'persuasion': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'pilot0': {
            'linkedApt': 'reflexes',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'pilot1': {
            'linkedApt': 'reflexes',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'pilot2': {
            'linkedApt': 'reflexes',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'programmming': {
            'linkedApt': 'cognition',
            'defaulting': false,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'protocol': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'psiAssault': {
            'linkedApt': 'willpower',
            'defaulting': false,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'psychosurgery': {
            'linkedApt': 'intuition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'research': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'scrounging': {
            'linkedApt': 'intuition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'seekerWeapons': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'sense': {
            'linkedApt': 'intuition',
            'defaulting': false,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'sprayWeapons': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'swimming': {
            'linkedApt': 'somatics',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'throwingWeapons': {
            'linkedApt': 'coordination',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'unarmedCombat': {
            'linkedApt': 'somatis',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        }
    },
    'knowledgeSkills': {
        'academics0': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'academics1': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'academics2': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'academics3': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'academics4': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'art0': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'art1': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'art2': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'art3': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'art4': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'interest0': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'interest1': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'interest2': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'interest3': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'interest4': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'language0': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'language1': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'language2': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'language3': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'language4': {
            'linkedApt': 'savvy',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'profession0': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'profession1': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'profession2': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'profession3': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
        'profession4': {
            'linkedApt': 'cognition',
            'defaulting': true,
            'base': undefined,
            'morphBonus': undefined,
            'total': undefined,
            'specializations': [],
        },
    },
    'reputation': {
        '@': undefined,
        'c': undefined,
        'e': undefined,
        'f': undefined,
        'g': undefined,
        'i': undefined,
        'r': undefined,
    },
    'muse': {},
    'morph': {
        'type': undefined,
        'class': undefined,
        'visibleAge': undefined,
        'visibleGender': undefined,
        'description': undefined,
        'aptitudes': {
            'cognition': undefined,
            'coordination': undefined,
            'intuition': undefined,
            'reflexes': undefined,
            'savvy': undefined,
            'somatics': undefined,
            'willpower': undefined
        },
        'stats': {
            'speedMod': undefined,
            'durability': undefined,
            'woundThreshold': undefined,
            'movementRate': undefined,
            'mobilitySystem': undefined
        },
        'aptitudeMax': undefined,
        'gear': {
            'internal': {
                'implants': [],
                'enhancements': [],
                'customizations': []
            }
        },
        'traits': [],
        'advantages': [],
    },
    'gear': {},
    'traits': {},
    'psi': {},
    ''
};

var $page = document.querySelector();